name: Deploy to Amazon ECS

on:
  push:
    branches:
      - features

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Deploy App Stack
        id: deploy
        uses: alexjurkiewicz/cfn-deploy@v2.0.1
        with:
          stackName: mayeul-marsaut-stack
          templateFile: CloudAwarenessLab/aws/cloudformation.yaml
      - name: EKS
        run: |
          sed -i "s#IMAGE_NAME#nypsyy/ssc#g" kustomization.yaml
          sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
          aws eks update-kubeconfig --name isen
          kubectl kustomize | kubectl apply -f -
      - name: Print App Hostname
        run: echo ${{ steps.deploy.outputs.cf_output_AppHostname }}
