name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Install NPM dependencies
      #   run: |
      #     npm install --production --unsafe-perm

      # - name: OWASP
      #   uses: sburris/dependency-check-action@master
      #   with:
      #     Project-Name: juice-shop

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v1.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: nypsyy/juice-shop
          tag_with_sha: true

      - name: Klar
        run: |
          wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64 -O klar
          chmod +x klar
          CLAIR_ADDR=http://clair.3r1.io:6060 ./klar nypsyy/juice-shop:sha-$(git rev-parse --short HEAD)

      - name: Load AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: EKS
        run: |
          sed -i "s#IMAGE_NAME#nypsyy/ssc#g" kustomization.yaml
          sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
          aws eks update-kubeconfig --name isen
          kubectl kustomize | kubectl apply -f -

      - name: Print App Hostname
        run: echo ${{ steps.deploy.outputs.cf_output_AppHostname }}
